### ISSUE TITLE
packing results in error

### ISSUE THREAD

**Issue by davesmits** [Microsoft/vsts-extension-build-release-tasks#64] opened 2018-03-10 18:13 UTC
since today packaging of my extension results in an error:

```
2018-03-10T18:08:02.0038988Z Checking tfx under: D:\a\_tools\tfx.cmd
2018-03-10T18:08:02.0059237Z Could not find tfx command. Preparing to install it under: D:\a\_tools\
2018-03-10T18:08:02.0406401Z [command]C:\Windows\system32\cmd.exe /D /S /C ""C:\Program Files\nodejs\npm.cmd" install tfx-cli --prefix D:\a\_tools\"
2018-03-10T18:08:15.2880253Z D:\a\_tools\tfx -> D:\a\_tools\node_modules\tfx-cli\_build\tfx-cli.js
2018-03-10T18:08:15.3299156Z + tfx-cli@0.5.6
2018-03-10T18:08:15.3300035Z added 172 packages in 12.123s
2018-03-10T18:08:15.3653212Z [command]C:\Windows\system32\cmd.exe /D /S /C "D:\a\_tools\tfx.cmd extension create --json --root D:\a\1\s\ActivityFeed.App\static --manifest-globs vss-extension.json --loc-root D:\a\1\s --publisher davesmits --extension-id VSTSActivityFeedDevelop --overrides-file "C:\Users\VSSADM~1\AppData\Local\Temp\PackageTask-0.253204.tmp" --output-path D:\a\1\s"
2018-03-10T18:08:15.3653771Z  0 [ '[command]C:\\Windows\\system32\\cmd.exe /D /S /C "D:\\a\\_tools\\tfx.cmd extension create --json --root D:\\a\\1\\s\\ActivityFeed.App\\static --manifest-globs vss-extension.json --loc-root D:\\a\\1\\s --publisher davesmits --extension-id VSTSActivityFeedDevelop --overrides-file "C:\\Users\\VSSADM~1\\AppData\\Local\\Temp\\PackageTask-0.253204.tmp" --output-path D:\\a\\1\\s"\r',
2018-03-10T18:08:15.3654608Z   '' ]
2018-03-10T18:08:15.3655621Z  1 [ '[command]C:\\Windows\\system32\\cmd.exe /D /S /C "D:\\a\\_tools\\tfx.cmd extension create --json --root D:\\a\\1\\s\\ActivityFeed.App\\static --manifest-globs vss-extension.json --loc-root D:\\a\\1\\s --publisher davesmits --extension-id VSTSActivityFeedDevelop --overrides-file "C:\\Users\\VSSADM~1\\AppData\\Local\\Temp\\PackageTask-0.253204.tmp" --output-path D:\\a\\1\\s"\r',
2018-03-10T18:08:15.3656155Z   '' ]
2018-03-10T18:08:16.8675922Z ##[warning][0m{
2018-03-10T18:08:16.8690662Z ##[warning]    "path": "D:\\a\\1\\s\\davesmits.VSTSActivityFeedDevelop-3.0.3007.vsix",
2018-03-10T18:08:16.8691158Z ##[warning]    "extensionId": "VSTSActivityFeedDevelop",
2018-03-10T18:08:16.8691525Z ##[warning]    "version": "3.0.3007",
2018-03-10T18:08:16.8691913Z ##[warning]    "publisher": "davesmits"
2018-03-10T18:08:16.8692246Z ##[warning]}[0m
2018-03-10T18:08:16.8772101Z ##[error]tfx failed with error: SyntaxError: Unexpected end of JSON input
```

**Comment by jessehouwing** [comment] 2018-03-10 18:23
Interesting. Looks like packaging actually succeeded, but the Jason
contains a BOM it seems. Can you install tfx 0.5.5 and see if that still
works, if that's the case it's a bug in tfx.

**Comment by davesmits** [comment] 2018-03-10 19:09
i just installed 0.5.5 global but still installs the newer version. how i make sure it uses the existing?

**Comment by jessehouwing** [comment] 2018-03-10 19:50
There is a hidden global variable that makes the task use the tfx from the
path.

**Comment by jessehouwing** [comment] 2018-03-10 19:56
Any value other then false will use the bloballybinstalled version:


tl.getVariable("vstsDevTools.buildTasks.checkGlobalTfx");

**Comment by davesmits** [comment] 2018-03-10 20:13
with 0.5.5 issue persists:

```
2018-03-10T20:04:01.4585459Z [command]C:\Windows\system32\cmd.exe /D /S /C ""C:\Program Files\nodejs\npm.cmd" install -g tfx-cli@0.5.5"
2018-03-10T20:05:05.0615013Z C:\npm\prefix\tfx -> C:\npm\prefix\node_modules\tfx-cli\_build\tfx-cli.js
2018-03-10T20:05:05.0616115Z + tfx-cli@0.5.5
2018-03-10T20:05:05.0616696Z added 172 packages in 58.425s
```

and then when packaging

```
2018-03-10T20:07:32.0230071Z Checking tfx globally
2018-03-10T20:07:32.0275785Z Found tfx globally C:\npm\prefix\tfx.cmd
2018-03-10T20:07:32.0492749Z [command]C:\Windows\system32\cmd.exe /D /S /C "C:\npm\prefix\tfx.cmd extension create --json --root D:\a\1\s\ActivityFeed.App\static --manifest-globs vss-extension.json --loc-root D:\a\1\s --publisher davesmits --extension-id VSTSActivityFeedDevelop --overrides-file "C:\Users\VSSADM~1\AppData\Local\Temp\PackageTask-0.783219.tmp" --output-path D:\a\1\s"
2018-03-10T20:07:32.0493551Z  0 [ '[command]C:\\Windows\\system32\\cmd.exe /D /S /C "C:\\npm\\prefix\\tfx.cmd extension create --json --root D:\\a\\1\\s\\ActivityFeed.App\\static --manifest-globs vss-extension.json --loc-root D:\\a\\1\\s --publisher davesmits --extension-id VSTSActivityFeedDevelop --overrides-file "C:\\Users\\VSSADM~1\\AppData\\Local\\Temp\\PackageTask-0.783219.tmp" --output-path D:\\a\\1\\s"\r',
2018-03-10T20:07:32.0493867Z   '' ]
2018-03-10T20:07:32.0494332Z  1 [ '[command]C:\\Windows\\system32\\cmd.exe /D /S /C "C:\\npm\\prefix\\tfx.cmd extension create --json --root D:\\a\\1\\s\\ActivityFeed.App\\static --manifest-globs vss-extension.json --loc-root D:\\a\\1\\s --publisher davesmits --extension-id VSTSActivityFeedDevelop --overrides-file "C:\\Users\\VSSADM~1\\AppData\\Local\\Temp\\PackageTask-0.783219.tmp" --output-path D:\\a\\1\\s"\r',
2018-03-10T20:07:32.0494782Z   '' ]
2018-03-10T20:07:33.7345456Z ##[warning][0m{
2018-03-10T20:07:33.7366645Z ##[warning]    "path": "D:\\a\\1\\s\\davesmits.VSTSActivityFeedDevelop-3.0.3017.vsix",
2018-03-10T20:07:33.7367418Z ##[warning]    "extensionId": "VSTSActivityFeedDevelop",
2018-03-10T20:07:33.7367865Z ##[warning]    "version": "3.0.3017",
2018-03-10T20:07:33.7368289Z ##[warning]    "publisher": "davesmits"
2018-03-10T20:07:33.7368656Z ##[warning]}[0m
2018-03-10T20:07:33.7480884Z ##[error]tfx failed with error: SyntaxError: Unexpected end of JSON input
```

my latest successful build was with 0.5.5

```
2018-03-07T21:51:13.3684557Z Checking tfx under: D:\a\_tools\tfx.cmd
2018-03-07T21:51:13.3703287Z Could not find tfx command. Preparing to install it under: D:\a\_tools\
2018-03-07T21:51:13.4016023Z [command]C:\Windows\system32\cmd.exe /D /S /C ""C:\Program Files\nodejs\npm.cmd" install tfx-cli --prefix D:\a\_tools\"
2018-03-07T21:51:26.1453317Z D:\a\_tools\tfx -> D:\a\_tools\node_modules\tfx-cli\_build\tfx-cli.js
2018-03-07T21:51:26.1820160Z + tfx-cli@0.5.5
2018-03-07T21:51:26.1821298Z added 172 packages in 11.143s
2018-03-07T21:51:26.2193678Z [command]C:\Windows\system32\cmd.exe /D /S /C "D:\a\_tools\tfx.cmd extension create --json --root D:\a\1\s\ActivityFeed.App\static --manifest-globs vss-extension.json --loc-root D:\a\1\s --publisher davesmits --extension-id VSTSActivityFeedDevelop --overrides-file "C:\Users\VSSADM~1\AppData\Local\Temp\PackageTask-0.302994.tmp" --output-path D:\a\1\s"
2018-03-07T21:51:26.2194359Z  0 [ '[command]C:\\Windows\\system32\\cmd.exe /D /S /C "D:\\a\\_tools\\tfx.cmd extension create --json --root D:\\a\\1\\s\\ActivityFeed.App\\static --manifest-globs vss-extension.json --loc-root D:\\a\\1\\s --publisher davesmits --extension-id VSTSActivityFeedDevelop --overrides-file "C:\\Users\\VSSADM~1\\AppData\\Local\\Temp\\PackageTask-0.302994.tmp" --output-path D:\\a\\1\\s"\r',
2018-03-07T21:51:26.2194720Z   '' ]
2018-03-07T21:51:26.2195188Z  1 [ '[command]C:\\Windows\\system32\\cmd.exe /D /S /C "D:\\a\\_tools\\tfx.cmd extension create --json --root D:\\a\\1\\s\\ActivityFeed.App\\static --manifest-globs vss-extension.json --loc-root D:\\a\\1\\s --publisher davesmits --extension-id VSTSActivityFeedDevelop --overrides-file "C:\\Users\\VSSADM~1\\AppData\\Local\\Temp\\PackageTask-0.302994.tmp" --output-path D:\\a\\1\\s"\r',
2018-03-07T21:51:26.2195555Z   '' ]
2018-03-07T21:51:27.8357664Z Packaged extension: D:\a\1\s\davesmits.VSTSActivityFeedDevelop-3.0.3004.vsix.
2018-03-07T21:51:27.8413224Z ##[section]Finishing: PackageVSTSExtension
```

**Comment by jessehouwing** [comment] 2018-03-10 20:18
Looks like the marketplace is returning invalid json.

```

##[warning]}�[0m

```

**Comment by davesmits** [comment] 2018-03-11 18:19
means vsts team need to fix?

**Comment by jessehouwing** [comment] 2018-03-11 18:21
I already contacted the team, like me they are travelling after the MVP
summit. I suspect it's the marketplace itself, not tfx.

**Comment by peterbarendse** [comment] 2018-03-12 13:25
I've the same issue. Using the "Hosted 2017" agent pool for my build. TFX version 0.5.6

> 2018-03-12T13:03:06.7561644Z ##[section]Starting: Package Extension
2018-03-12T13:03:06.7762565Z ==============================================================================
2018-03-12T13:03:06.7762915Z Task         : Package Extension
2018-03-12T13:03:06.7763116Z Description  : Package a Team Services extension into a VSIX file
2018-03-12T13:03:06.7763352Z Version      : 1.1.44
2018-03-12T13:03:06.7763459Z Author       : Microsoft Corporation
2018-03-12T13:03:06.7763590Z Help         : 
2018-03-12T13:03:06.7763701Z ==============================================================================
2018-03-12T13:03:08.2453832Z Checking tfx under: D:\a\_tools\tfx.cmd
2018-03-12T13:03:08.2461290Z Could not find tfx command. Preparing to install it under: D:\a\_tools\
2018-03-12T13:03:08.2577471Z [command]C:\Windows\system32\cmd.exe /D /S /C ""C:\Program Files\nodejs\npm.cmd" install tfx-cli --prefix D:\a\_tools\"
2018-03-12T13:03:51.3833921Z D:\a\_tools\tfx -> D:\a\_tools\node_modules\tfx-cli\_build\tfx-cli.js
2018-03-12T13:03:51.4196053Z + tfx-cli@0.5.6
2018-03-12T13:03:51.4196587Z added 172 packages in 28.747s
2018-03-12T13:03:51.4507040Z [command]C:\Windows\system32\cmd.exe /D /S /C "D:\a\_tools\tfx.cmd extension create --json --root D:\a\3\s --manifest-globs vss-extension.json --loc-root D:\a\3\s --publisher peterbarendse --overrides-file "C:\Users\VSSADM~1\AppData\Local\Temp\PackageTask-0.166979.tmp" --output-path D:\a\3\a"
2018-03-12T13:03:51.4507395Z 
2018-03-12T13:03:52.0176495Z 
2018-03-12T13:03:52.2769034Z ##[warning][0m{
2018-03-12T13:03:52.3075997Z ##[warning]    "path": "D:\\a\\3\\a\\peterbarendse.WindowsLogOffUsers-0.0.1.vsix",
2018-03-12T13:03:52.3076857Z ##[warning]    "extensionId": "WindowsLogOffUsers",
2018-03-12T13:03:52.3078283Z ##[warning]    "version": "1.0.1",
2018-03-12T13:03:52.3078722Z ##[warning]    "publisher": "peterbarendse"
2018-03-12T13:03:52.3079110Z ##[warning]}[0m
2018-03-12T13:03:52.3449141Z ##[error]tfx failed with error: SyntaxError: Unexpected end of JSON input
2018-03-12T13:03:52.3527702Z ##[section]Finishing: Package Extension

Last succesful build was with also with version 0.5.6, packaged on 3-9-2018

**Comment by jessehouwing** [comment] 2018-03-12 13:28
I'm talking to the team that builds `tfx` and the marketplace team. I suspect the issue will magically go away soonish. Or at least that's what I hope.

**Comment by mpseidel** [comment] 2018-03-13 08:47
Some error here. Works on Hosted Linux Preview though.

**Comment by trevorsg** [comment] 2018-03-13 15:06
This should be fixed in tfx-cli now. There was a small breaking change introduced into a dependency, which turned into a rather large breaking change. There is also a new command line option, `--no-color`, which suppresses outputting any color marker bytes.

**Comment by peterbarendse** [comment] 2018-03-13 15:36
It works as intended again. Thanks for the fix!

**Closed** 2018-03-14 20:20 UTC
